### ISSUE TITLE
React 16 warning

### ISSUE THREAD

**Issue by tizmagik** [tizmagik/react-head#1]
Figure out why React 16 shows this warning:

```
Warning: Expected server HTML to contain a matching <title> in <div>.
```

You can see this in action with the example app:

```
npm run build
cd example
npm install
npm start
```

Then navigate to http://localhost:3000

**Comment by coymeetsworld** [comment]
I'll take a look

**Comment by adamgruber** [comment]
A quick look shows this might be an issue with using portals to render content outside of the root element. When React hydrates the DOM, it looks for a matching element in the server HTML but in this case can't find a `<title>` tag inside the root element so it throws a warning. Not sure this is fixable since this is the behavior you are going for.

**Comment by tizmagik** [comment]
Heh yea, this might be a use of React Portals in a way it wasn't intended to be used. But the use case feels legit! I'm hoping it's just a false negative warning or something.

Will try and get @gaearon 's attention sometime to see if this is legit or a hacky use of Portals that he recommends against. 😁

**Comment by gaearon** [comment]
File an issue in React with an isolated small example please.

**Comment by tizmagik** [comment]
Filed https://github.com/facebook/react/issues/11169
