### ISSUE TITLE
data-rh attribute

### ISSUE THREAD

**Issue by CanRau** [tizmagik/react-head#40]
Hi, just stumbled upon your module, while trying to evaluate the use of React Portals for <head> and as your plugin proofs it does indeed 👍 
haven't had the time to test it out yet, but I was actually looking for an alternative to react-helmet because this https://github.com/nfl/react-helmet/issues/79 kind of bugs me..

not sure how big of an impact this has, but wanted to try it out and didn't liked the idea of hacking the attribute away like mentioned in the comments..

any thoughts on this?

by the way, in my case I'm using [GatsbyJs](https://github.com/gatsbyjs/gatsby)

**Comment by CanRau** [comment]
it bugs people in the mentioned comment https://github.com/nfl/react-helmet/issues/79#issuecomment-305266240 and I'm not sure how real it is for SEO as some worry..
probably it's not a thing..

**Comment by TrySound** [comment]
There is a mention in this comment about these attributes shouldn't affect software outside of the site. So maybe we should open issues in failed validators.

People also mention google AMP breaking. I wonder to know why they use react in AMP which is a kind of framework without scripts or something.

**Comment by CanRau** [comment]
they're probably generating AMPs using react?!

**Comment by tizmagik** [comment]
Using React for AMP pages is a good use case (we currently do this at NYT), but in that case, since you don't care about the client-side heat tags being updated (not much if any client-side JS executes) you can regexp the data attribute out before sending the server markup.

Otherwise, as @TrySound suggested, this attribute is used so react-head knows which tags it's responsible for updating/removing. I'm not sure of another way to do this same thing.

**Comment by CanRau** [comment]
So the issue can be closed if those attributes have no impact 👍 

@TrySound yeah I had thought about validator issues rather than "real" problems, too 🥇

**Comment by tizmagik** [comment]
Thanks @CanRau

**Comment by outofthisworld** [comment]
Can you generate hash to identify instead of a data attribute?

**Comment by TrySound** [comment]
And where do you suggest to store this hash?
